### ISSUE TITLE
Emote keybinding in script dpemotes

### ISSUE THREAD

**Issue by kamelzarandah** [rdephillip/MidnightRP#16]
Players with controllers who use the emote bind command can scuff up their controller usage.
Players are unable to reset or delete their keybinds on their own and we have to do it for them in the data base everytime. 

would like to find a way where we can allow players to remove keybinds
or take out the feature of keybinding completely. (can be done by commenting out the command to do it)

**Comment by rdephillip** [comment]
This was something brought up when I was on SRP and I provided them information on how to fix it. While they may have ignored it we have the opportunity to shine here.

Disabling this would be non-ideal as I know several that like the custom keybinding. So an "unbind" solution is by far a better solution.

**Comment by Broebie** [comment]
I can take a look at this if nobody else is working on this one yet

**Comment by Broebie** [comment]
Added a new command for users to unset emote keybinds
